Switching to app based routing
psan2/spvsp-next pull request #2
Opened 2023-08-19 19:36 UTC by davidfunnell

-Switched from Page base routing to App based routing with Nextjs13
-Created expected pages in app directory
-Created Navbar and added Links to each of the created pages
-Added "isActive" to link to show currently active page
-Created config/SiteConfig file for main navbar items
-Added types/index.ts file with a type for main nav bar items
-Added personal picture of west for header image to /public

2023-08-19 23:21 UTC, psan2 requested changes
Mostly nitpicks! Functionally looks fine, but policing code style is what we have to do when we don’t have eslint really dialed in 😬 thanks dude!

2023-08-19 23:21 UTC, psan2 commented on src/app/contact/page.tsx
> +interface pageProps {
Nitpick - TS types are PascalCase by convention, so this would be PageProps.

I’d also encourage giving you types a specific name even though in this scope it’s the only PageProps around - when debugging, seeing ContactPageProps is much more informative than PageProps. We also don’t need to be worried about optimizing for size, because types get removed at compile time and will never see prod.

2023-08-19 23:21 UTC, psan2 commented on src/app/contact/page.tsx
> +const page: FC<pageProps> = ({}) => {
Same with naming specificity here - React components are PascalCase by convention, and we should be as specific as is helpful. I’d call this ContactPage.

FWIW, standard conventions are:

React components - PascalCase
TS interfaces and types - PascalCase
JS/TS functions or variables - camelCase
TS enums - WHATEVER_THIS_IS

I’d give the rest of these components a pass with the naming convention and specificity in mind 👍

2023-08-19 23:21 UTC, psan2 commented on src/app/page.tsx
> +  return <div>Home Page</div>;
Nitpick - we prefer not to export an anonymous function. It’s just a readability thing, but it’s easier to do this as

const HomePage = () => {};

export default HomePage;

2023-08-19 23:21 UTC, psan2 commented on src/components/Navbar.tsx
> +                  key={link.title}
Personal preference, but I’d use href instead of title. In theory a target URL will be slightly more unique? 🤷‍♂️

2023-08-20 05:04 UTC, psan2 commented on src/app/contact/page.tsx
> +export default ContactPage
Not a blocker for now, but just noticed this - make sure you get the prettier extension installed in your vscode, and probably change your settings to Format on Save. I'll get a prettierrc file in here later.

tl;dr - it's good to use an autoformatter, and if one person on a project doesn't then you end up in this situation where the next person in this file is going to create a bunch of whitespace changes when their formatter adds semicolons to this whole file.

2023-08-20 05:05 UTC, psan2 commented on src/config/SiteConfig.ts
> +  ] satisfies MainNavBarItems[],
Fancy new TS4.9 shit! Nice.

2023-08-20 05:05 UTC, psan2 approved these changes

2023-08-20 05:06 UTC, merged

2023-08-20 05:10 UTC, davidfunnell commented on src/config/SiteConfig.ts
> +  MainNavBar: [
Should I update MainNavBar be mainNavBar?